var OpticoTracker=(function(){var _urls={view:typeof opticoTrackingViewUrl!=='undefined'?opticoTrackingViewUrl:"//www.optico.fr/client-statistics/view",click:typeof opticoTrackingClickUrl!=='undefined'?opticoTrackingClickUrl:"//www.optico.fr/client-statistics/click",event:typeof opticoTrackingEventUrl!=='undefined'?opticoTrackingEventUrl:"//www.optico.fr/trackJsEvent.php"};var _options;var _defaultOptions={trackingRestrictionParameters:{},trackingRestrictionOperator:'OR',phoneMatching:{ignoreDefaultPattern:false,pattern:null,length:null,minLength:null,maxLength:null,matchingNumber:null},clickMobileDirectCall:false,trackingTypeAssociation:{}};var _directDisplay;var _countryCode;var _color='';var _clickColor='';var _visitId;var _uniqueVisitorId;var _pageView;var _withPhoneNumbers=false;var _surtaxedNumbers;
function _getDirectDisplayValue(){return typeof opticoDirectDisplay!=='undefined'?opticoDirectDisplay:false}
function _getCountryCodeValue(){return typeof opticoCountryCode!=='undefined'?opticoCountryCode:33}
function _getPhoneColorValue(){return typeof opticoPhoneColor!=='undefined'?opticoPhoneColor:''}
function _getClickColorValue(){return typeof opticoClickColor!=='undefined'?opticoClickColor:''}
function _initOptions(){if(_options){return}if(typeof opticoOptions!=='undefined'){_options=OpticoMiscellaneous.extend(_defaultOptions,opticoOptions)}else{_options=_defaultOptions}}
function _checkTrackingRestrictions(){var trackingRestrictionParameters=_options.trackingRestrictionParameters;var trackingRestrictionOperator=_options.trackingRestrictionOperator;if(_getCookie('visitId')||OpticoMiscellaneous.isEmpty(trackingRestrictionParameters)){return true}var isOrOperator=trackingRestrictionOperator.toUpperCase()==='OR';var enabled=!isOrOperator;for(var parameterName in trackingRestrictionParameters){if(trackingRestrictionParameters.hasOwnProperty(parameterName)) {var parameterRestrictionValue = trackingRestrictionParameters[parameterName];var queryParameterValue = OpticoMiscellaneous.getQueryParameterByName(parameterName);if (isOrOperator) {if (queryParameterValue.length && (parameterRestrictionValue == '*' || queryParameterValue == parameterRestrictionValue)) {return true}} else {if (queryParameterValue.length && (parameterRestrictionValue != '*' && queryParameterValue != parameterRestrictionValue)) {return false}}}}return enabled}
function _hasPhoneNumbers(){return OpticoPhoneManager.getPhoneNumbers().length>0}
function _phoneReplacement(phone,elemId,isLink){if(typeof isLink==='undefined'){isLink=false}var container=document.createElement("div");container.id="optico-phone-"+elemId;if(isLink){container.setAttribute('name','link')}container.style.display="inline";if(_getClickColorValue()){container.style.color=_getClickColorValue()}container.style.cursor="pointer";container.onclick=function(){_trackClick(phone,container.id)};container.appendChild(document.createTextNode("Afficher le numéro"));return container}
function _surtaxPhoneLinkReplacement(surtaxedPhone){var container=document.createElement("a");container.setAttribute('href','tel:'+OpticoMiscellaneous.cleanPhone(surtaxedPhone.surtaxPhoneNumber));if(_getPhoneColorValue()){container.setAttribute('style','color:'+_getPhoneColorValue())}container.appendChild(document.createTextNode(surtaxedPhone.surtaxPhoneNumber +(surtaxedPhone.surtaxPhoneCode?' Code: '+surtaxedPhone.surtaxPhoneCode:'')));return container}
function _surtaxPhoneTextReplacement(surtaxedPhone){var surtaxPhone=surtaxedPhone.surtaxPhoneNumber;if(surtaxedPhone.surtaxPhoneCode){surtaxPhone +=' Code: '+surtaxedPhone.surtaxPhoneCode}var container=null;if(_getPhoneColorValue()){container=document.createElement("span");container.setAttribute('style','color:'+_getPhoneColorValue());container.appendChild(document.createTextNode(surtaxPhone))}else{container=document.createTextNode(surtaxPhone)}return container}
function _isRobot(){var userAgent=navigator.userAgent.toLowerCase();var isRobot=false;var robots=["teoma","alexa","froogle","gigabot","inktomi","looksmart","url_spider_sql","firefly","nationaldirectory","ask jeeves","tecnoseek","infoseek","webfindbot","girafabot","crawler","www.galaxy.com","googlebot","scooter","slurp","msnbot","bingbot","appie","fast","webbug","spade","zyborg","rabaz","baiduspider","feedfetcher-google","technoratisnoop","rankivabot","mediapartners-google","sogou web spider","webalta crawler","tweetmemebot","butterfly","twitturls","me.dium","twiceler","libcurl","solomon.ru","exabot","exalead","ahrefsbot","voilabot","amazonaws","rate-limited-proxy","google-proxy","brg8.com","pingdom","yashni","softlayer.com","dotbot","yandex","wise-guys","bezeqint","mail.ru","kundencontroller","monitorengine","proximic","spider","uptimerobot","robot","adsbot"];for(var i=0; i < robots.length; i++){if(userAgent.indexOf(robots[i])>-1){isRobot=true;break}}return isRobot}
function _setCookie(name,value,expireAfter){var expires;expireAfter=expireAfter||30*60*1000;var date=new Date();date.setTime(date.getTime()+expireAfter);expires="; expires="+date.toGMTString();document.cookie="optico_"+name+"="+value+expires+"; path=/"}
function _getCookie(c_name){c_name="optico_"+c_name;if(document.cookie.length>0){c_start=document.cookie.indexOf(c_name+"=");if(c_start!==-1){c_start=c_start+c_name.length+1;c_end=document.cookie.indexOf(";",c_start);if(c_end===-1){c_end=document.cookie.length}return unescape(document.cookie.substring(c_start,c_end))}}return ""}
function _generateRandomId(){return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g,function(c){var r=Math.random()*16|0,v=c=='x'?r:r&0x3|0x8;return v.toString(16)})}
function _setUniqueVisitorId(){_uniqueVisitorId=_generateRandomId();_setCookie('unique_visitor_id',_uniqueVisitorId,50*365*24*60*60*1000)}
function _getUniqueVisitorId(){if(!_uniqueVisitorId){_uniqueVisitorId=_getCookie('unique_visitor_id');if(!_uniqueVisitorId){_setUniqueVisitorId()}}return _uniqueVisitorId}
function _trackClick(phone,domId,callback){callback=callback||'OpticoTracker.replace';var url=_urls.click+"?page_url="+encodeURIComponent(window.location.toString())+"&phone="+encodeURIComponent(phone)+"&view_id="+encodeURIComponent(_pageView)+"&dom_id="+domId+"&callback="+callback+"&is_mobile="+encodeURIComponent(OpticoMiscellaneous.isMobile());if(!OpticoMiscellaneous.isEmpty(_options.trackingTypeAssociation)){url+="&tracking_types="+encodeURIComponent(JSON.stringify(_options.trackingTypeAssociation));}OpticoMiscellaneous.include(url)}
return{
_sleep:function(milliseconds){var start=new Date().getTime();for(var i=0;i<1e7;i++){if((new Date().getTime()-start)>milliseconds){break}}},
getOptions:function(){_initOptions();return _options},
getCountryCode:function(){return _countryCode},
setVisitId:function(visitId){_visitId=visitId;_setCookie('visitId',visitId)},
setViewId:function(viewId){_pageView=viewId},
getVisitId:function(){return _visitId},
getViewId:function(){return _pageView},
pageView:function(){if(!_isRobot()){_directDisplay=_getDirectDisplayValue();_countryCode=_getCountryCodeValue();_color=_getPhoneColorValue();_clickColor=_getClickColorValue();_withPhoneNumbers=_hasPhoneNumbers();_initOptions();if(!_checkTrackingRestrictions()){return}var url=_urls.view+"?page_url="+encodeURIComponent(window.location.toString())+"&page_title="+encodeURIComponent(document.title)+"&phones="+encodeURIComponent(OpticoPhoneManager.getPhoneNumbers())+"&nr_phones="+encodeURIComponent(OpticoPhoneManager.getPhoneNumbers().length)+"&is_mobile="+encodeURIComponent(OpticoMiscellaneous.isMobile())+"&visit_id="+_getCookie('visitId')+"&unique_view_id="+encodeURIComponent(OpticoMiscellaneous.getOpticoRandId())+"&unique_visitor_id="+encodeURIComponent(_getUniqueVisitorId());if(document.referrer!==""){url+="&referer_url="+encodeURIComponent(document.referrer)}if(!OpticoMiscellaneous.isEmpty(_options.trackingTypeAssociation)){url+="&tracking_types="+encodeURIComponent(JSON.stringify(_options.trackingTypeAssociation));}if(_directDisplay){url+="&direct_display=true&callback=OpticoTracker.directDisplay"}else{url+="&callback=OpticoTracker.ajaxClick"}OpticoMiscellaneous.include(url)}},
ajaxClick:function(response){if(response){var surtaxReplacementNodeIndex=0;var nodes=OpticoMiscellaneous.getTextNodes(document.body);for(var i=0; i<nodes.length; i++){var toRemove=false;var isLink=nodes[i].nodeType===1&&nodes[i].nodeName==='A';var text=null;var phoneNumbers=null;if(isLink){text=nodes[i].getAttribute('href');phoneNumbers=OpticoPhoneManager.parse(text)}else{text=nodes[i].nodeValue;phoneNumbers=OpticoPhoneManager.parse(text)}if(phoneNumbers.length>0){for(var j=0; j < phoneNumbers.length; j++){toRemove=false;if(response.indexOf(phoneNumbers[j])>-1){var pos=text.indexOf(phoneNumbers[j]);if(pos>0){if(nodes[i].nodeType===1&&nodes[i].nodeName==='A'){text=text.substr(0,pos)}else{nodes[i].parentNode.insertBefore(document.createTextNode(text.substr(0,pos)),nodes[i])}toRemove=true}nodes[i].parentNode.insertBefore(_phoneReplacement(phoneNumbers[j],surtaxReplacementNodeIndex++,isLink),nodes[i]);toRemove=true;text=text.substr(pos+phoneNumbers[j].length)}}if((isLink&&phoneNumbers.length>0)||(! isLink&&text.length>0)){nodes[i].parentNode.insertBefore(document.createTextNode(text),nodes[i]);toRemove=true}if(toRemove){nodes[i].parentNode.removeChild(nodes[i])}}}OpticoFormManager.trackForms()}},
directDisplay:function(response){if(response){_surtaxedNumbers=response;var nodes=OpticoMiscellaneous.getTextNodes(document.body);for(var i=0; i < nodes.length; i++){var text='';if(nodes[i].nodeType===1&&nodes[i].nodeName==='A'){text=nodes[i].getAttribute('href')}else{text=nodes[i].nodeValue}var phoneNumbers=OpticoPhoneManager.parse(text);var found=false;if(phoneNumbers.length>0){for(var j=0; j < phoneNumbers.length; j++){if(_surtaxedNumbers[phoneNumbers[j]]){found=true;var pos=text.indexOf(phoneNumbers[j]);if(pos>0){if(nodes[i].nodeType===1&&nodes[i].nodeName==='A'){text=text.substr(0,pos)}else{nodes[i].parentNode.insertBefore(document.createTextNode(text.substr(0,pos)),nodes[i])}}if(nodes[i].nodeType===1&&nodes[i].nodeName==='A'){text +=OpticoMiscellaneous.cleanPhone(_surtaxedNumbers[phoneNumbers[j]].surtaxPhoneNumber)}else{nodes[i].parentNode.insertBefore(_surtaxPhoneTextReplacement(_surtaxedNumbers[phoneNumbers[j]]),nodes[i]);text=text.substr(pos+phoneNumbers[j].length)}}}if(found){if(nodes[i].nodeType===1&&nodes[i].nodeName==='A'){nodes[i].setAttribute('href',text)}else if(text.length>0){nodes[i].parentNode.insertBefore(document.createTextNode(text),nodes[i])}if(nodes[i].nodeType===3){nodes[i].parentNode.removeChild(nodes[i])}}}}OpticoFormManager.trackForms()}},
replace:function(response){if(response&&typeof response.domId!=='undefined'){var elem=document.getElementById(response.domId);var new_elem=null;var isMobile = OpticoMiscellaneous.isMobile();if(response.surtaxPhone){if(elem.getAttribute('name')==='link' || (isMobile && _options.clickMobileDirectCall)){new_elem=_surtaxPhoneLinkReplacement(response.surtaxPhone);}else{new_elem=_surtaxPhoneTextReplacement(response.surtaxPhone)}}else{new_elem=document.createTextNode('Numéro non disponible')}if(isMobile && _options.clickMobileDirectCall){new_elem.click();}elem.parentNode.insertBefore(new_elem,elem);elem.parentNode.removeChild(elem)}},
trackPhone:function(phone,domId,callback){_trackClick(phone,domId,callback)},
trackEvent:function(category,action,label,value){category=category||null;action=action||null;label=label||null;value=value||null;var url=_urls.event+"?visit_id="+_getCookie('visitId')+"&view_id="+OpticoTracker.getViewId()+"&page_url="+encodeURIComponent(window.location.toString())+(category?"&category="+encodeURIComponent(category):'')+(action?"&action="+encodeURIComponent(action):'')+(label?"&label="+encodeURIComponent(label):'')+(value!==null?"&value="+encodeURIComponent(value):'');OpticoMiscellaneous.include(url);OpticoTracker._sleep(500)}}})();
var OpticoPhoneManager=(function(){var _phoneNumbers=false;var _phoneMatchingOptions=false;
function _initOptions(){if(false===_phoneMatchingOptions){var options=OpticoTracker.getOptions();_phoneMatchingOptions=options.phoneMatching}}
function _pushUsedDefinedPatternPhones(str,list){if(null===_phoneMatchingOptions.pattern){return}while(match=_phoneMatchingOptions.pattern.exec(str)){cleanPhone=match[0].replace(/\+/g,"00");cleanPhone=cleanPhone.replace(/\D/g,"");if(_phoneMatchingOptions.length&&cleanPhone.length!==_phoneMatchingOptions.length){continue}if(_phoneMatchingOptions.minLength&&cleanPhone.length<_phoneMatchingOptions.minLength){continue}if(_phoneMatchingOptions.maxLength&&cleanPhone.length>_phoneMatchingOptions.maxLength){continue}if(_phoneMatchingOptions.matchingNumber){list.push(String(match[_phoneMatchingOptions.matchingNumber]))}else{list.push(String(match[0]))}}}
return{
parse:function(str){var list=[];_initOptions();if (_phoneMatchingOptions.ignoreDefaultPattern!==true){var regex=new RegExp("((00|\\+)?([\\s\\(\\)-.]{1})?"+OpticoTracker.getCountryCode()+"([\\s\\(\\)-.]{1})?)?((\\(0\\))|0)?(\\s)?([1-9]|\\([1-9]\\))(?:([\\s\\(\\)-./]{1})?[0-9]{2}){4}","g");while(match=regex.exec(str)){var cleanPhone=match[0].replace(/\+/g,"00");cleanPhone=cleanPhone.replace(/\D/g,"");if(cleanPhone.length>9){list.push(String(match[0]))}}}_pushUsedDefinedPatternPhones(str,list);return list},
getPhoneNumbers:function(){if(_phoneNumbers===false)_phoneNumbers=OpticoPhoneManager.parse(document.body.innerHTML);return _phoneNumbers}};})();
var OpticoFormManager=(function(){var _url=typeof opticoTrackingFormUrl!=='undefined'?opticoTrackingFormUrl:"//www.optico.fr/trackJsForm.php";var _abandonedForms=[];
function _getFormTrackingEnabledValue(){return typeof opticoFormTrackingEnabled!=='undefined'?opticoFormTrackingEnabled:false}
function _getOpticoFormClass(form){var formClass=form.className.match(/OpticoForm\d+/);if(formClass.length){return formClass[0]}return null}
function _serialize(form){var i,j,values,data={};for(i=0;i<form.elements.length;i++){var e=form.elements[i];if(e.name===""){continue}switch(e.nodeName){case 'INPUT':switch(e.type){case 'password':case 'file':case 'button':case 'reset':case 'submit':break;case 'checkbox':if(e.checked){if(typeof data[e.name]==='undefined'){data[e.name]=[e.value]}else{data[e.name].push(e.value)}}break;case 'radio':if(e.checked){data[e.name]=e.value}break;default:if(e.value){data[e.name]=e.value}break}break;case 'TEXTAREA':if(e.value){data[e.name]=e.value}break;case 'SELECT':switch(e.type){case 'select-one':if(e.value){data[e.name]=e.value}break;case 'select-multiple':values=[];for(j=0;j<e.options.length;j++){if(e.options[j].selected){values.push(e.options[j].value)}}if(values.length){data[e.name]=values}break}break}}return data}
function _buildUrl(form,isAbandoned){isAbandoned=isAbandoned||false;return _url+"?visit_id="+OpticoTracker.getVisitId()+"&view_id="+OpticoTracker.getViewId()+"&page_url="+encodeURIComponent(window.location.toString())+"&action_url="+encodeURIComponent(form.action)+"&data="+encodeURIComponent(JSON.stringify(_serialize(form)))+"&is_abandoned="+isAbandoned.toString()+"&form_class_name="+_getOpticoFormClass(form)}
return{
trackForms:function(){if(_getFormTrackingEnabledValue()){var forms=document.getElementsByTagName("form");for(var i=0;i<forms.length;i++){var className="OpticoForm"+i;forms[i].className+=forms[i].className?" "+className:className;forms[i].onsubmit=function(e){OpticoFormManager.trackFormSubmit(e)};var formElements=forms[i].elements;for(var j=0;j<formElements.length;j++){formElements[j].onchange=function(e){OpticoFormManager.changeFormElem(e)}}}var onBeforeUnLoadEvent=false;window.onunload=window.onbeforeunload=function(){if(!onBeforeUnLoadEvent){onBeforeUnLoadEvent=true;OpticoFormManager.trackFormUnload()}}}},
changeFormElem:function(event){var formElem=event.target||event.srcElement;var formClass=_getOpticoFormClass(formElem.form);if(formClass&&_abandonedForms.indexOf(formClass)==-1){_abandonedForms.push(formClass)}},
trackFormSubmit:function(e){e.stopPropagation();e.preventDefault();var form=e.target||e.srcElement;var removeFromAbandonedForms=_abandonedForms.indexOf(_getOpticoFormClass(form));if(removeFromAbandonedForms!=-1){_abandonedForms.splice(removeFromAbandonedForms,1)}OpticoMiscellaneous.include(_buildUrl(form))},
trackFormUnload:function(){for(var i=0;i<_abandonedForms.length;i++){var form=document.getElementsByClassName(_abandonedForms[i]);if(form.length){OpticoMiscellaneous.include(_buildUrl(form[0],true));OpticoTracker._sleep(1000)}}},
originalSubmit:function(formClassName){var form=document.getElementsByClassName(formClassName);if(form.length){form[0].onsubmit=null;form[0].submit()}}}})();
var OpticoMiscellaneous=(function(){return{
isEmpty:function(object){for(var prop in object){if(object.hasOwnProperty(prop))return false;}return true},
cleanPhone:function(phone){var cleanPhone=phone.replace(/\+/g,"00");return cleanPhone.replace(/\D/g,"")},
extend:function(defaultOptions,config){var extended={};for(var prop in defaultOptions){if(defaultOptions.hasOwnProperty(prop)){extended[prop]=(config[prop]===null||typeof config[prop]==='undefined')?defaultOptions[prop]:config[prop]}}return extended},
hasQueryParameter:function(name){return location.search.indexOf('?'+name+'=')>=0||location.search.indexOf('&'+name+'=')>=0},
getQueryParameterByName:function(name){name=name.replace(/[\[]/,"\\\[").replace(/[\]]/,"\\\]");var regex=new RegExp("[\\?&]"+name+"=([^&#]*)"),results=regex.exec(location.search);return results===null ? "" : decodeURIComponent(results[1].replace(/\+/g," "))},
checkValidScript:function(){if(OpticoMiscellaneous.getQueryParameterByName('check_validity')){top.postMessage('valid','*');}},
getTextNodes:function(node){var nodes=[];if(node.hasChildNodes()){var child=node.firstChild;while(child){if(child.nodeType===1&&child.nodeName!=='SCRIPT'){if(child.nodeType===1&&child.nodeName==='A'){nodes=nodes.concat(child)}nodes=nodes.concat(OpticoMiscellaneous.getTextNodes(child))}else if(child.nodeType===3){nodes=nodes.concat(child)}child=child.nextSibling}}return nodes},
include:function(url){var script=document.createElement("script");script.setAttribute("src",url);script.setAttribute("type","text/javascript");script.onload=function(){this.parentNode.removeChild(this)};document.getElementsByTagName("head")[0].appendChild(script)},
getOpticoRandId:function(){return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g,function(c){var r=Math.random()*16|0,v=c=='x'?r:r&0x3|0x8;return v.toString(16);})},
isMobile:function(){var check=false;(function(a){var patt1=new RegExp("(android|bb\d+|meego).+mobile|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(hone|od)|iris|kindle|lge |maemo|midp|mmp|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|series(4|6)0|symbian|treo|up\.(browser|link)|vodafone|wap|windows(ce|phone)|xda|xiino","i");var patt2=new RegExp("1207|6310|6590|3gso|4thp|50[1-6]i|770s|802s|a wa|abac|ac(er|oo|s\-)|ai(ko|rn)|al(av|ca|co)|amoi|an(ex|ny|yw)|aptu|ar(ch|go)|as(te|us)|attw|au(di|\-m|r |s )|avan|be(ck|ll|nq)|bi(lb|rd)|bl(ac|az)|br(e|v)w|bumb|bw\-(n|u)|c55\/|capi|ccwa|cdm\-|cell|chtm|cldc|cmd\-|co(mp|nd)|craw|da(it|ll|ng)|dbte|dc\-s|devi|dica|dmob|do(c|p)o|ds(12|\-d)|el(49|ai)|em(l2|ul)|er(ic|k0)|esl8|ez([4-7]0|os|wa|ze)|fetc|fly(\-|_)|g1 u|g560|gene|gf\-5|g\-mo|go(\.w|od)|gr(ad|un)|haie|hcit|hd\-(m|p|t)|hei\-|hi(pt|ta)|hp( i|ip)|hs\-c|ht(c(\-| |_|a|g|p|s|t)|tp)|hu(aw|tc)|i\-(20|go|ma)|i230|iac( |\-|\/)|ibro|idea|ig01|ikom|im1k|inno|ipaq|iris|ja(t|v)a|jbro|jemu|jigs|kddi|keji|kgt( |\/)|klon|kpt |kwc\-|kyo(c|k)|le(no|xi)|lg( g|\/(k|l|u)|50|54|\-[a-w])|libw|lynx|m1\-w|m3ga|m50\/|ma(te|ui|xo)|mc(01|21|ca)|m\-cr|me(rc|ri)|mi(o8|oa|ts)|mmef|mo(01|02|bi|de|do|t(\-| |o|v)|zz)|mt(50|p1|v )|mwbp|mywa|n10[0-2]|n20[2-3]|n30(0|2)|n50(0|2|5)|n7(0(0|1)|10)|ne((c|m)\-|on|tf|wf|wg|wt)|nok(6|i)|nzph|o2im|op(ti|wv)|oran|owg1|p800|pan(a|d|t)|pdxg|pg(13|\-([1-8]|c))|phil|pire|pl(ay|uc)|pn\-2|po(ck|rt|se)|prox|psio|pt\-g|qa\-a|qc(07|12|21|32|60|\-[2-7]|i\-)|qtek|r380|r600|raks|rim9|ro(ve|zo)|s55\/|sa(ge|ma|mm|ms|ny|va)|sc(01|h\-|oo|p\-)|sdk\/|se(c(\-|0|1)|47|mc|nd|ri)|sgh\-|shar|sie(\-|m)|sk\-0|sl(45|id)|sm(al|ar|b3|it|t5)|so(ft|ny)|sp(01|h\-|v\-|v )|sy(01|mb)|t2(18|50)|t6(00|10|18)|ta(gt|lk)|tcl\-|tdg\-|tel(i|m)|tim\-|t\-mo|to(pl|sh)|ts(70|m\-|m3|m5)|tx\-9|up(\.b|g1|si)|utst|v400|v750|veri|vi(rg|te)|vk(40|5[0-3]|\-v)|vm40|voda|vulc|vx(52|53|60|61|70|80|81|83|85|98)|w3c(\-| )|webc|whit|wi(g |nc|nw)|wmlb|wonu|x700|yas\-|your|zeto|zte\-","i");if(patt1.test(a)||patt2.test(a.substr(0,4))){check=true}})(navigator.userAgent||navigator.vendor||window.opera);return check}};})();
OpticoMiscellaneous.checkValidScript();OpticoTracker.pageView();
